name: Build Dylib for MacOS

on:
  push:
    branches:
      - master
      - dev
    # tags: '*'
  release:
    types:
      - created
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2]
        julia-arch: [x64]
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Build
        run: deps/build_dylib_macos.sh
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: deps/gh-update-to-release
